### ISSUE TITLE
Downloads for non-latest no longer work

### ISSUE THREAD

**Issue by TrueBrain** [ich777/docker-openttd-server#1]
Hi!

Currently your Dockers fail to download any non-latest OpenTTD version. This is because you reference an outdated URL:

https://github.com/ich777/docker-openttd-server/blob/9750b71f3516793f1c3301a3f7ee061ed2379cdf/scripts/start-server.sh#L33

This was an URL that was never meant to be used by the general public (and OpenTTD never actively promoted it), and it has been disabled several months back in favour of the new CDN at https://cdn.openttd.org/ . Updating the URL to there, should fix the problem and make everything working again.

Additionally, while at it, can I suggest to also change the URL here too:

https://github.com/ich777/docker-openttd-server/blob/9750b71f3516793f1c3301a3f7ee061ed2379cdf/scripts/start-server.sh#L26

`proxy.binaries.openttd.org` retried over a year ago, and has also been replaced by https://cdn.openttd.org/ . There is still a redirect active on `proxy.binaries.openttd.org` to point to the new place, but that will be disabled in a few months too. In general, possibly this test for `latest` is no longer needed in the new setup OpenTTD uses, as both latest and any older version area available on the same URL.

On https://cdn.openttd.org/ there are a few folders of interest to you:

https://cdn.openttd.org/openttd-releases/ <- for all and any official releases ever done by OpenTTD
https://cdn.openttd.org/opengfx-releases/ <- for all and any official OpenGFX releases

Possibly you could update https://github.com/ich777/docker-openttd-server/blob/master/README.md#env-params to make OpenGFX point to the new URL, and also bump the version to `0.6.0`, the latest. The URL currently used will remain active for the time being, but will not receive any new versions.

If you would be able to fix this, that would be great. Thank you!

PS: if you want to verify `cdn.openttd.org` is the correct URL: check the download links on https://www.openttd.org/downloads/openttd-releases/latest.html

**Comment by ich777** [comment]
I will change and update the container as soon as possible (today or tomorrow) ;)

**Comment by ich777** [comment]
@TrueBrain I tested the container and it works as intended and also the download is working (a log from your side will be nice).
I chould change the downloadlink I think if that's necessary.

And the updated of the GFX package is no problem ;)

[openttd.log](https://github.com/ich777/docker-openttd-server/files/5465186/openttd.log)

**Comment by ich777** [comment]
@TrueBrain Issue is now solved. 

Cleaned up the code a little bit, I also added a new veriable 'GFX_PK_V' if you set it to latest it will always pull the newest version from the grapics pack on container start/restart (customized the container this way that if a user update an existing container it will pull always the latest graphics pack even if the variable is not set by default).

Depricated now the variable 'GFXPACK_URL' (you can leave it in if you don't want to edit anything).

EDIT: Btw thank you for reporting this! Really appreciated!
