### ISSUE TITLE
Libglomp is missing, causing the container to crash

### ISSUE THREAD

**Issue by highlyprofessionalusername** [ich777/docker-openttd-server#2]
Output when pulling the code and building the container:

`---Ensuring UID: 99 matches user---
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---Trying to get latest stable OpenTTD version...---
---Latest stable OpenTTD version is: 14.0---
---Getting latest OpenGFX version...---
---Latest OpenGFX version is: 7.1---
---Version Check---

-------------------------------------
---OpenTTD not found! Downloading,---
-----and installing v14.0-----
-------------------------------------
/serverdata/serverf 100%[===================>]  20.84M  15.4MB/s    in 1.4s
---Successfully downloaded OpenTTD v14.0---
---OpenGFX not found, downloading...---
/serverdata/serverf 100%[===================>]   3.38M  15.4MB/s    in 0.2s
---Successfully downloaded OpenGFX---
Archive:  /serverdata/serverfiles/opengfx-7.1.zip
  inflating: opengfx-7.1.tar
---Prepare Server---
---Checking for old logs---
---Server ready---
---Start Server---
/serverdata/serverfiles/openttd: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
Terminated`

The fix is editing [the Dockerfile](https://github.com/ich777/docker-openttd-server/blob/master/Dockerfile#L7) to read
`apt-get -y install --no-install-recommends unzip xz-utils curl screen libgomp1 libglib2.0-dev && \`

**Comment by ich777** [comment]
@highlyprofessionalusername please see my comment [here](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=1408450), container is fixed. If you experience any further related issue feel free to reopen the issue or create a new one.
